import { ProfileData } from "./profile";

export const profileEn: ProfileData = {
  personal: {
    name: "Amar Mehdaoui",
    title: "Senior Full-Stack Engineer & Cloud Architect | SaaS • AI • Kubernetes",
    bio: "Senior Full-Stack Developer (React, Next.js, TypeScript, Node.js, Python) and Certified Cloud Architect (AWS, GCP, Azure, Kubernetes, Terraform). 9+ years designing multi-tenant SaaS platforms, event-driven microservices and AI/LLM solutions. Combined Dev + Ops + AI expertise: from code to K8s deployment, from API to RAG pipeline. Track record: Fortune 500 enterprises (Orange Business), FinTech scale-ups, and product building from scratch (Fidelya SaaS).",
    avatar: "/avatar.jpg",
    email: "amar@stellarwave.fr",
    phone: "+33 6 25 05 97 32",
    location: "Paris, France (Full Remote)",
    linkedin: "https://linkedin.com/in/amar-mehdaoui",
    github: "https://github.com/amarmehdaouiocb",
    website: "https://stellarwave.fr",
    availability: "Available immediately",
    tjm: "€700 - €950/day",
  },
  stats: [
    { label: "Years of Experience", value: "9+" },
    { label: "Projects Delivered", value: "50+" },
    { label: "Cloud Certifications", value: "5" },
    { label: "FinOps Savings", value: "-18%" },
  ],
  skills: [
    {
      title: "Full-Stack",
      color: "#3b82f6",
      skills: [
        { name: "React / Next.js 15", level: "expert" },
        { name: "TypeScript / JavaScript", level: "expert" },
        { name: "Node.js / Express / Fastify", level: "expert" },
        { name: "Python / FastAPI", level: "advanced" },
        { name: "Tailwind CSS / Framer Motion", level: "expert" },
        { name: "tRPC / Prisma / Drizzle", level: "advanced" },
      ],
    },
    {
      title: "Databases & APIs",
      color: "#10b981",
      skills: [
        { name: "PostgreSQL / Supabase", level: "expert" },
        { name: "Redis / Kafka", level: "advanced" },
        { name: "REST / GraphQL / gRPC", level: "expert" },
        { name: "Event-Driven / CQRS", level: "advanced" },
        { name: "MongoDB / DynamoDB", level: "advanced" },
        { name: "Elasticsearch", level: "intermediate" },
      ],
    },
    {
      title: "Cloud & DevOps",
      color: "#f59e0b",
      skills: [
        { name: "AWS (ECS, Lambda, RDS, S3, CDK)", level: "expert" },
        { name: "GCP / Azure", level: "advanced" },
        { name: "Kubernetes / Helm / Istio", level: "advanced" },
        { name: "Terraform / Pulumi", level: "advanced" },
        { name: "CI/CD (GitHub Actions, GitLab)", level: "expert" },
        { name: "Datadog / Prometheus / Grafana", level: "advanced" },
      ],
    },
    {
      title: "AI & Architecture",
      color: "#8b5cf6",
      skills: [
        { name: "LangChain / LlamaIndex / RAG", level: "advanced" },
        { name: "OpenAI API / Claude API", level: "advanced" },
        { name: "Vector DB (Pinecone, Weaviate)", level: "intermediate" },
        { name: "Multi-tenant SaaS Architecture", level: "expert" },
        { name: "Microservices / DDD", level: "expert" },
        { name: "FinOps / Cost Optimization", level: "expert" },
      ],
    },
  ],
  experience: [
    {
      role: "Founder & Lead Full-Stack Developer",
      company: "Fidelya",
      location: "Full Remote",
      period: "2025 - Present",
      type: "freelance",
      achievements: [
        "Architected and built from scratch a B2B multi-tenant SaaS for restaurant loyalty (React, TypeScript, Node.js, Supabase)",
        "Frontend: React/TypeScript SPA with real-time dashboards, role-based access (admin/cashier), advanced analytics",
        "Backend: Node.js/Express REST APIs, PostgreSQL with Row Level Security, event-driven architecture, automated campaign engine",
        "AI Integration: RAG pipeline with LangChain + Azure AI Document Intelligence for OCR and semantic receipt analysis",
        "Features: QR code loyalty, Apple Wallet passes, automated omnichannel campaigns (SMS, WhatsApp, email, push)",
      ],
      stack: ["React", "TypeScript", "Node.js", "Supabase", "PostgreSQL", "LangChain", "Azure AI", "Vercel"],
    },
    {
      role: "Cloud Solution Architect",
      company: "Orange Business",
      location: "Paris (Hybrid → Remote)",
      period: "January 2020 - December 2024",
      type: "cdi",
      achievements: [
        "Designed multi-cloud architectures (AWS, Azure, GCP) for 15+ Fortune 500 and mid-market enterprise accounts",
        "Pre-sales technical lead: RFP responses (€500K-5M), technical workshops, C-level presentations, POC delivery",
        "Led microservices/Kubernetes migrations: HLD/LLD, IaC with Terraform, CI/CD pipelines, Datadog monitoring",
        "FinOps: achieved 18% annual cloud cost reduction via tagging policies, rightsizing, Reserved Instances",
        "Embedded FinTech scale-up mission (6 months): monolith → 12 K8s microservices, Istio service mesh, multi-region EU/US",
      ],
      stack: ["AWS", "Azure", "GCP", "Kubernetes", "Istio", "Terraform", "Python", "TypeScript", "GitLab CI", "Datadog"],
    },
    {
      role: "Freelance Cloud & DevOps Consultant",
      company: "Independent",
      location: "Full Remote",
      period: "November 2018 - December 2019",
      type: "freelance",
      achievements: [
        "Short-term engagements for SMBs/startups: AWS migrations, CI/CD setup, Docker/K8s containerization",
        "Built internal automation tools: Python scripts, Slack bots, third-party API integrations",
        "Continuous learning and cloud certification preparation (AWS, GCP) — obtained later",
        "Open source contributions: merged PRs on terraform-aws-modules, community Terraform module improvements",
      ],
      stack: ["AWS", "Docker", "Kubernetes", "Terraform", "Python", "Ansible", "CI/CD"],
    },
    {
      role: "DevOps Engineer",
      company: "Orange",
      location: "Paris, France",
      period: "September 2017 - October 2018",
      type: "cdi",
      achievements: [
        "Built full-stack internal application (Python/JS) and automated critical data workflows",
        "Large-scale data migration using Talend ETL — 100% data integrity, zero downtime",
        "Implemented CI/CD pipelines: 37% deployment time reduction, automated testing",
        "DevOps evangelism: trained dev/ops teams on GitFlow, monitoring, alerting best practices",
      ],
      stack: ["Python", "JavaScript", "Talend ETL", "Jenkins", "Docker", "PostgreSQL", "Linux"],
    },
    {
      role: "Full-Stack Developer & DevOps",
      company: "Devoto",
      location: "Paris, France",
      period: "April 2015 - September 2017",
      type: "cdi",
      achievements: [
        "Built proprietary CMS/ERP from scratch in .NET — n-tier architecture, REST API, responsive frontend",
        "Delivered 17 client websites with optimized performance (< 3s load time) and SEO-friendly architecture",
        "IIS/SQL Server administration and L3 support — 99.5% SLA, 94% critical incidents resolved < 4h",
      ],
      stack: [".NET", "C#", "JavaScript", "SQL Server", "IIS", "Windows Server"],
    },
  ],
  certifications: [
    { name: "AWS Solutions Architect Associate", issuer: "Amazon Web Services", date: "2023" },
    { name: "Google Cloud Professional Cloud Architect", issuer: "Google Cloud", date: "2023" },
    { name: "Certified Kubernetes Application Developer (CKAD)", issuer: "CNCF", date: "2022" },
    { name: "Terraform Associate", issuer: "HashiCorp", date: "2022" },
    { name: "Azure Fundamentals (AZ-900)", issuer: "Microsoft", date: "2021" },
  ],
  projects: [
    {
      name: "Fidelya — B2B SaaS",
      description: "AI-powered multi-tenant SaaS for restaurant loyalty. Scalable architecture: React/TypeScript frontend, Node.js/Supabase backend with RLS, RAG pipeline LangChain + Azure AI for OCR and semantic analysis. Features: QR loyalty, Apple Wallet, omnichannel campaigns.",
      tech: ["React", "TypeScript", "Node.js", "Supabase", "PostgreSQL", "LangChain", "Azure AI", "Vercel"],
    },
    {
      name: "DocuMind — AI Assistant",
      description: "AI assistant for semantic search in technical documentation. RAG pipeline: smart chunking, OpenAI embeddings, Pinecone vector search, contextual generation. React interface with streaming responses.",
      tech: ["Python", "LangChain", "OpenAI API", "Pinecone", "FastAPI", "React", "TypeScript"],
    },
    {
      name: "FinTech Migration — Scale-up",
      description: "Orange Business embedded mission: Java monolith → 12 Kubernetes microservices migration. Istio service mesh, multi-region EU/US for GDPR compliance, 40% time-to-market reduction.",
      tech: ["Kubernetes", "Istio", "AWS EKS", "Terraform", "GitLab CI", "Datadog", "Java", "Go"],
    },
    {
      name: "Stellar Wave — Studio",
      description: "My freelance studio — Premium Next.js 15 landing page with automated acquisition, smart forms, analytics and Vercel CI/CD deployment.",
      tech: ["Next.js 15", "Tailwind CSS 4", "Framer Motion", "Resend", "Vercel"],
      url: "https://stellarwave.fr",
    },
    {
      name: "Open Source Contributions",
      description: "Active contributions: terraform-aws-modules (optimized ECS module), Supabase (RLS patterns documentation), LangChain (RAG examples). 15+ merged PRs.",
      tech: ["Terraform", "TypeScript", "Python", "Supabase", "LangChain"],
    },
  ],
  education: [
    { degree: "Master of Science — Cloud & Big Data", school: "ITESCIA, Cergy-Pontoise", year: "2018" },
    { degree: "DUT in Computer Science", school: "University Paris 13, Villetaneuse", year: "2015" },
  ],
  languages: [
    { name: "French", level: "Native" },
    { name: "English", level: "Fluent (C1, TOEIC 950)" },
    { name: "Arabic", level: "Professional working proficiency" },
    { name: "Spanish", level: "Upper-intermediate (B2)" },
  ],
};
